"""Shared pipeline schema and policy contracts."""

from pathlib import Path


DEFAULT_CHUNKSIZE = 500_000
STRING_DTYPE = "string"
STRICT_PARSING_ERRORS = "raise"
CSV_WRITE_MODE = "w"
CSV_APPEND_MODE = "a"

TRANSACTIONS_CACHE_FILENAME = "transactions.csv"
CUSTOMERS_CACHE_FILENAME = "customers.csv"
ARTICLES_CACHE_FILENAME = "articles.csv"
IMAGE_FEATURES_CACHE_FILENAME = "product_images.csv"
PRODUCT_FEATURES_CACHE_FILENAME = "product_features.csv"
RFM_OUTPUT_FILENAME = "rfm.csv"

RAW_TRANSACTIONS_FILENAME = "transactions_train.csv"
RAW_CUSTOMERS_FILENAME = "customers.csv"
RAW_ARTICLES_FILENAME = "articles.csv"

CUSTOMER_ID_COLUMN = "customer_id"
RAW_ARTICLE_ID_COLUMN = "article_id"
PRODUCT_ID_COLUMN = "product_id"
ORDER_DATE_COLUMN = "order_date"
UNIT_PRICE_COLUMN = "unit_price"
RAW_DATE_COLUMN = "t_dat"
RAW_PRICE_COLUMN = "price"
CUSTOMER_AGE_COLUMN = "age"
CUSTOMER_MEMBERSHIP_COLUMN = "club_member_status"
PRODUCT_NAME_COLUMN = "product_name"
RAW_PRODUCT_NAME_COLUMN = "prod_name"
IMAGE_PATH_COLUMN = "image_path"
PRODUCT_NAME_LENGTH_COLUMN = "product_name_length"
IMAGE_MEAN_COLUMN = "image_mean"
IMAGE_STD_COLUMN = "image_std"

RAW_TRANSACTION_REQUIRED_COLUMNS = (
    RAW_DATE_COLUMN,
    CUSTOMER_ID_COLUMN,
    RAW_ARTICLE_ID_COLUMN,
    RAW_PRICE_COLUMN,
)
RAW_TRANSACTION_DTYPES = {
    CUSTOMER_ID_COLUMN: STRING_DTYPE,
    RAW_ARTICLE_ID_COLUMN: STRING_DTYPE,
}
RAW_CUSTOMER_REQUIRED_COLUMNS = (
    CUSTOMER_ID_COLUMN,
    CUSTOMER_AGE_COLUMN,
    CUSTOMER_MEMBERSHIP_COLUMN,
)
RAW_ARTICLE_REQUIRED_COLUMNS = (
    RAW_ARTICLE_ID_COLUMN,
    RAW_PRODUCT_NAME_COLUMN,
)
TRANSACTION_RENAMES = {
    RAW_DATE_COLUMN: ORDER_DATE_COLUMN,
    RAW_ARTICLE_ID_COLUMN: PRODUCT_ID_COLUMN,
    RAW_PRICE_COLUMN: UNIT_PRICE_COLUMN,
}
ARTICLE_RENAMES = {
    RAW_ARTICLE_ID_COLUMN: PRODUCT_ID_COLUMN,
    RAW_PRODUCT_NAME_COLUMN: PRODUCT_NAME_COLUMN,
}

TRANSACTION_NORMALIZED_REQUIRED_COLUMNS = (
    CUSTOMER_ID_COLUMN,
    PRODUCT_ID_COLUMN,
    ORDER_DATE_COLUMN,
    UNIT_PRICE_COLUMN,
)
CUSTOMER_NORMALIZED_REQUIRED_COLUMNS = (
    CUSTOMER_ID_COLUMN,
    CUSTOMER_AGE_COLUMN,
    CUSTOMER_MEMBERSHIP_COLUMN,
)
ARTICLE_NORMALIZED_REQUIRED_COLUMNS = (
    PRODUCT_ID_COLUMN,
    PRODUCT_NAME_COLUMN,
    IMAGE_PATH_COLUMN,
)
IMAGE_FEATURE_REQUIRED_COLUMNS = (
    PRODUCT_ID_COLUMN,
    IMAGE_PATH_COLUMN,
    PRODUCT_NAME_LENGTH_COLUMN,
    IMAGE_MEAN_COLUMN,
    IMAGE_STD_COLUMN,
)

DEFAULT_RFM_CUSTOMER_COLUMN = CUSTOMER_ID_COLUMN
DEFAULT_RFM_DATE_COLUMN = ORDER_DATE_COLUMN
DEFAULT_RFM_AMOUNT_COLUMN = UNIT_PRICE_COLUMN
DEFAULT_RFM_PARTITION_COUNT = 64
RFM_REFERENCE_OFFSET_DAYS = 1
RFM_SCORE_QUANTILE_COUNT = 4
RFM_SCORE_LABELS = (1, 2, 3, 4)
RFM_HIGH_SCORE_MIN = 3
RFM_BEST_SCORE = 4
RFM_LOW_SCORE_MAX = 2
RFM_SEGMENT_COLUMN = "segment"
RFM_RECENCY_COLUMN = "recency"
RFM_FREQUENCY_COLUMN = "frequency"
RFM_MONETARY_COLUMN = "monetary"
RFM_RECENCY_SCORE_COLUMN = "r_score"
RFM_FREQUENCY_SCORE_COLUMN = "f_score"
RFM_MONETARY_SCORE_COLUMN = "m_score"
RFM_SEGMENT_VIP = "VIP"
RFM_SEGMENT_LOYAL = "Loyal"
RFM_SEGMENT_NEW = "New"
RFM_SEGMENT_CHURNED = "Churned"
RFM_SEGMENT_POTENTIAL = "Potential"
RFM_REQUIRED_COLUMNS = (
    CUSTOMER_ID_COLUMN,
    RFM_RECENCY_COLUMN,
    RFM_FREQUENCY_COLUMN,
    RFM_MONETARY_COLUMN,
    RFM_RECENCY_SCORE_COLUMN,
    RFM_FREQUENCY_SCORE_COLUMN,
    RFM_MONETARY_SCORE_COLUMN,
    RFM_SEGMENT_COLUMN,
)
